#!/bin/bash

set -e

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
platform=`uname -a | awk '{print tolower($1)}'`
arch=`uname -m`
version="4.4.4.2-1aa3781c5-dirty"
url="https://github.com/MeowcoinProject/Meowcoin/releases/download"
tag="V1.0.3"

if [ "${platform}" == "linux" ]; then
    if [ "${arch}" == "x86_64" ]; then
        archive_name="MEOW-${version}-CLI-x86_64-linux-gnu.tar.gz"
    elif [ "${arch}" == "x86_32" ]; then
        archive_name="MEOW-${version}-CLI-i686-pc-linux-gnu.tar.gz"
    elif [[ "${arch}" =~ "arm" ]]; then
        # e.g. raven-4.1.0.0-arm-linux-gnueabihf.tar.gz
        archive_name="MEOW-${version}-CLI-arm-linux-gnueabihf.tar.gz"
    else
        echo "Meowcoin binary distribution not found for linux architecture: ${arch}"
        exit -1
    fi
elif [ "${platform}" == "darwin" ]; then
    archive_name="MEOW-${version}-CLI-OSX.zip"
else
    echo "Meowcoin binary distribution not found for platform and architecture (${platform}/${arch})"
    exit -1
fi

binary_url="${url}/${tag}/${archive_name}"
shasums_url="${url}/${tag}/${archive_name}.SHA256SUMS"

download_meowcoind() {

    cd "${root_dir}/bin"

    if test -e "meowcoind"; then
        echo "\"bin/meowcoind\" already exists -- skipping download."
        return;
    fi

    echo "Downloading meowcoin: ${binary_url}"

    is_curl=true
    if hash curl 2>/dev/null; then
        curl --fail -I $binary_url >/dev/null 2>&1
    else
        is_curl=false
        wget --server-response --spider $binary_url >/dev/null 2>&1
    fi

    if test $? -eq 0; then
        if [ "${is_curl}" = true ]; then
            curl -L $binary_url > $archive_name
            curl -L $shasums_url > SHA256SUMS.asc
        else
            wget $binary_url
            wget $shasums_url
        fi
        if test -e "${archive_name}"; then
            echo "Unpacking meowcoin distribution"
            if [[ "${platform}" == "linux" ]]; then            
                tar -xvzf $archive_name
                if test $? -eq 0; then
                    ln -sf "MEOW-${version}/bin/meowcoind"
                    return;
                fi
            elif [[ "${platform}" == "darwin" ]]; then
                hdiutil mount $archive_name
                if test $? -eq 0; then
                    cp /Volumes/Meowcoin\ Core/Meowcoin-Qt.app/Contents/MacOS/meowcoind .
                    hdiutil unmount /Volumes/Meowcoin\ Core
                    return;
                fi
            fi
        fi
    fi
    echo "Meowcoin binary distribution could not be downloaded"
    exit -1
}

verify_download() {
    echo "Verifying signatures of meowcoin download"
    gpg --verify "${root_dir}/bin/SHA256SUMS.asc"

    if hash shasum 2>/dev/null; then
        shasum_cmd="shasum -a 256"
    else
        shasum_cmd="sha256sum"
    fi

    download_sha=$(${shasum_cmd} "${root_dir}/bin/${archive_name}" | awk '{print $1}')
    expected_sha=$(cat "${root_dir}/bin/SHA256SUMS.asc" | grep "${archive_name}" | awk '{print $1}')
    echo "Checksum (download): ${download_sha}"
    echo "Checksum (verified): ${expected_sha}"
    if [ "${download_sha}" != "${expected_sha}" ]; then
        echo -e "\033[1;31mChecksums did NOT match!\033[0m\n"
        exit 1
    else
        echo -e "\033[1;32mChecksums matched!\033[0m\n"
    fi
}

download=1
verify=0

if [ "${SKIP_MEOWCOIN_DOWNLOAD}" = 1 ]; then
    download=0;
fi

if [ "${VERIFY_MEOWCOIN_DOWNLOAD}" = 1 ]; then
    verify=1;
fi

while [ -n "$1" ]; do
  param="$1"
  value="$2"

  case $param in
    --skip-meowcoin-download)
          download=0
          ;;
    --verify-meowcoin-download)
          verify=1
          ;;
  esac
  shift
done

if [ "${download}" = 1 ]; then
    download_meowcoind
fi

if [ "${verify}" = 1 ]; then
    verify_download
fi

exit 0
